'use client'
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog"
import { IoFlagOutline, IoInformationCircleOutline, IoSwapHorizontalOutline } from "react-icons/io5"
import { H2, P14, P16 } from "./typography"
import { LuArrowRightFromLine, LuBox } from "react-icons/lu"
import { PiClockClockwiseFill } from "react-icons/pi"
import { MdOutlineCheckCircleOutline, MdQuestionMark } from "react-icons/md"
import { FaRegStopCircle } from "react-icons/fa"
export default function TypesModal() {
    return (
        <Dialog>
            <DialogTrigger><IoInformationCircleOutline size={16} />
            </DialogTrigger>
            <DialogContent showCloseButton={false} className="rounded-xl">
                <DialogHeader className="hidden">
                    <DialogTitle>{''}</DialogTitle>
                </DialogHeader>
                <H2 className="text-center text-primary">Transaction Types</H2>
                <div className="space-y-4 mt-4">
                    <div className="flex items-start gap-4">
                        <LuBox size={20} className="mt-0.5" />
                        <div className="space-y-1">
                            <P16 className="font-bold">Block Metadata</P16>
                            <P14 className="leading-5 text-gray/60">System-generated transactions that provide additional data for each confirmed block.</P14>
                        </div>
                    </div>
                    <div className="flex items-start gap-4">
                        <LuArrowRightFromLine size={20} className="mt-0.5" />
                        <div className="space-y-1">
                            <P16 className="font-bold">Genesis Transaction</P16>
                            <P14 className="leading-5 text-gray/60">The first transaction in the Cedra blockchain.</P14>
                        </div>
                    </div>
                    <div className="flex items-start gap-4">
                        <IoSwapHorizontalOutline size={20} className="mt-0.5" />
                        <div className="space-y-1">
                            <P16 className="font-bold">User Transaction</P16>
                            <P14 className="leading-5 text-gray/60">A transaction generated by users of the Cedra blockchain.</P14>
                        </div>
                    </div>
                    <div className="flex items-start gap-4">
                        <PiClockClockwiseFill size={20} className="mt-0.5" />
                        <div className="space-y-1">
                            <P16 className="font-bold">Pending Transaction</P16>
                            <P14 className="leading-5 text-gray/60">A transaction currently in the mempool waiting to be committed.</P14>
                        </div>
                    </div>
                    <div className="flex items-start gap-4">
                        <IoFlagOutline size={20} className="mt-0.5" />
                        <div className="space-y-1">
                            <P16 className="font-bold">State Checkpoint</P16>
                            <P14 className="leading-5 text-gray/60">System-generated transactions that save the latest state of the Cedra blockchain.</P14>
                        </div>
                    </div>
                    <div className="flex items-start gap-4">
                        <MdOutlineCheckCircleOutline size={20} className="mt-0.5" />
                        <div className="space-y-1">
                            <P16 className="font-bold">Validator Transaction</P16>
                            <P14 className="leading-5 text-gray/60">Validator metadata transactions.</P14>
                        </div>
                    </div>
                    <div className="flex items-start gap-4">
                        <FaRegStopCircle size={20} className="mt-0.5" />
                        <div className="space-y-1">
                            <P16 className="font-bold">Block Epilogue Transaction</P16>
                            <P14 className="leading-5 text-gray/60">Block epilogue transactions describing end state of a block.</P14>
                        </div>
                    </div>
                    <div className="flex items-start gap-4">
                        <MdQuestionMark size={20} className="mt-0.5" />
                        <div className="space-y-1">
                            <P16 className="font-bold">Unknown type: unknown</P16>
                            <P14 className="leading-5 text-gray/60">Unknown transaction type unknown.</P14>
                        </div>
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    )
}